{{/* SPDX-License-Identifier: BUSL-1.1 */}}
{{- if and .Values.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "audit-evidence-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audit-evidence-runner.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "audit-evidence-runner.selectorLabels" . | nindent 6 }}
{{- end }}
