{{/* SPDX-License-Identifier: BUSL-1.1 */}}
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auditforge.fullname" . }}-app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auditforge.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.storeKind }}
    name: {{ .Values.externalSecrets.storeName }}
  target:
    name: {{ include "auditforge.fullname" . }}-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.postgres.key }}
        property: {{ .Values.externalSecrets.remoteRefs.postgres.property }}
    - secretKey: redis-password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.redis.key }}
        property: {{ .Values.externalSecrets.remoteRefs.redis.property }}
    - secretKey: meilisearch-master-key
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.meilisearch.key }}
        property: {{ .Values.externalSecrets.remoteRefs.meilisearch.property }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.remoteRefs.minio.key }}
{{- end }}
